<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\RoomBooking.Contracts\RoomBooking.Contracts.csproj" />
      <ProjectReference Include="..\RoomBooking.Domain\RoomBooking.Domain.csproj" />
    </ItemGroup>

</Project>
